sigstore/rekor-search-ui

.github/workflows/format.yaml
.github/workflows/reviewdog.yaml

- ESLint
- Prettier
- Action linter
- EOF newline, trailing spaces
- Do not submit

Add basic GitHub actions

---

src/modules/rekor/components/search_form.tsx

- Revalidate when changing attribute
- Reset validation when changing fields

Fix validation issues

---

src/modules/rekor/components/rekor_explorer.tsx

To make it easy to copy/paste links around.

Update query params with searches

---

src/modules/components/SearchForm.tsx

Add help text for the Commit SHA field

---

src/modules/components/HashedRekord.tsx

Support non-cert PKs

---

src/modules/x509/extensions.ts

Remove prefixes from certificate extensions

---

package.json
src/pages/_app.tsx
yarn.lock

The Fathom tracking account is owned by @chainguard-dev

Add fathom tracking

---

.github/workflows/format.yaml
src/pages/_app.tsx

Removes Fathom Analytics from the site.

Remove Fathom Analytics

---

src/modules/components/Entry.tsx

fix ref to Intoto schema type

---

next.config.js

Remove the base path so that images work in prod and dev

Remove base path from Next config

---

src/modules/x509/extensions.ts

Support for properly rendering the new Fulcio certificate extensions.
**Before:**
**After:**

support rendering of new fulcio cert extensions

---

src/pages/_document.tsx

add lang attr to root html tag

---

src/modules/components/Entry.tsx
src/modules/components/Intoto001.tsx
src/modules/components/Intoto002.tsx

There are still many applications that upload intoto v001 entries, so adding back support.
Fixes https://github.com/sigstore/rekor-search-ui/issues/69

Add support for intoto v0.0.1 entries

---

.github/dependabot.yml

configure dependabot for updating GHA and node

---

.github/workflows/nextjs.yml
.github/workflows/reviewdog.yaml

setup node version from package.json

---

.github/dependabot.yml
.github/workflows/nextjs.yml
.github/workflows/reviewdog.yaml
src/modules/components/SearchForm.tsx

set required field

---

src/modules/x509/extensions.ts

fix changed API call

---

next-env.d.ts
next.config.js

enable static export

---

.github/workflows/nextjs.yml

remove step from GHA

---

package.json
src/modules/x509/extensions.ts

backdown x509 dep

---

package-lock.json

run npm install

---

.github/workflows/unit-tests.yaml
package-lock.json
package.json

Bump node from 18.x to 22.x

---

src/modules/components/Entry.tsx

fix loading PEM encoded cert as yaml
